// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilihnrkwgpuoukdfndxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsaWhucmt3Z3B1b3VrZGZuZHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDA4OTIsImV4cCI6MjA1OTMxNjg5Mn0.iWeBLtXxZe2lBLN_2EvJfp80iMwAj5lXDUXXJDYNRGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);